# Generated by Django 6.0.7 on 2026-07-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_has_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_password",
            field=models.BooleanField(default=False),
        ),
    ]
