# Generated by Django 6.0.7 on 2026-07-18 18:42

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category.", max_length=50, unique=True
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Slug for the category.", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="InteractionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the interaction type.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Slug for the category.", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction type",
                "verbose_name_plural": "Interaction types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the skill.", max_length=80),
                ),
                (
                    "slug",
                    models.CharField(help_text="Slug for the skill.", max_length=80),
                ),
                ("fluency_window", models.IntegerField(default=100)),
                ("stability_threshold", models.IntegerField(default=20)),
                ("target_accuracy", models.FloatField(default=0.85)),
                ("target_speed", models.FloatField(default=5)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category of the skill.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="engine.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["category", "name"],
                "unique_together": {("category", "name"), ("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the skill level.", max_length=80
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Slug of the skill level.", max_length=80
                    ),
                ),
                (
                    "json_schema",
                    models.JSONField(
                        blank=True,
                        help_text="JSON schema for the prompt data associated with this skill level. Required for schema validation.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the skill level.",
                        null=True,
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        blank=True,
                        help_text="Template string for displaying the prompt, e.g., '{multiplicand1} \\times {multiplicand2}'.",
                        null=True,
                    ),
                ),
                (
                    "interaction_config",
                    models.CharField(
                        blank=True,
                        help_text="UI interaction details.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "skill_level_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Position of the skill level in the sequence of skill levels for the skill.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the skill.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_levels_by_category",
                        to="engine.category",
                    ),
                ),
                (
                    "parent",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Slugs of parent levels of the skill.",
                        to="engine.skilllevel",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill of the skill level.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_levels_by_skill",
                        to="engine.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill level",
                "verbose_name_plural": "Skill levels",
                "ordering": ["skill", "skill_level_rank", "name"],
                "unique_together": {("skill", "name"), ("skill", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guest_username",
                    models.CharField(
                        blank=True,
                        help_text="Username provided by a guest user for this session.",
                        max_length=50,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="The UTC timestamp when the session started."
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="The UTC timestamp when the session ended."
                    ),
                ),
                ("total_correct", models.PositiveIntegerField()),
                ("total_incorrect", models.PositiveIntegerField()),
                ("device_info", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Username of the registered user for this session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="engine.skill",
                    ),
                ),
                (
                    "user_skill_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's skill level at the time of the session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.skilllevel",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_time"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data defining the content of the prompt. JSON Schema defined in Skill Level instance.",
                    ),
                ),
                ("operand1", models.IntegerField(blank=True, null=True)),
                ("operand2", models.IntegerField(blank=True, null=True)),
                (
                    "correct_response",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "correct_response_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Correct numerical response for the prompt.",
                        null=True,
                    ),
                ),
                (
                    "correct_response_string",
                    models.CharField(
                        blank=True,
                        help_text="Correct string response for the prompt.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "correct_response_array",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="Correct array response for the prompt.",
                        null=True,
                    ),
                ),
                (
                    "prompt_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Position of the prompt in a sequence of prompts at this skill level.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skill_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Level of the skill targeted by the prompt.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.skilllevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "ordering": ["skill_level", "prompt_rank"],
            },
        ),
        migrations.CreateModel(
            name="UserSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_skill_level", models.PositiveIntegerField(default=1)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_index",
                    models.PositiveIntegerField(
                        help_text="Index of this response in the session."
                    ),
                ),
                ("was_correct", models.BooleanField()),
                (
                    "time_spent_ms",
                    models.PositiveIntegerField(
                        help_text="Time spend on prompt in milliseconds."
                    ),
                ),
                (
                    "interaction_config",
                    models.CharField(
                        blank=True,
                        help_text="UI interaction details.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_response",
                    models.CharField(
                        help_text="User's submitted response.", max_length=255
                    ),
                ),
                (
                    "interaction_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Interaction type of the response.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.interactiontype",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="engine.prompt",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="engine.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "sequence_index"],
                "unique_together": {("session", "sequence_index")},
            },
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="engine_prom_data_3f7764_gin"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("skill_level", "data")},
        ),
        migrations.AlterUniqueTogether(
            name="userskillprofile",
            unique_together={("user", "skill")},
        ),
    ]
