# Generated by Django 6.0.7 on 2026-07-19 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def populate_pseudonyms(apps, schema_editor):
    Player = apps.get_model("engine", "Player")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Session = apps.get_model("engine", "Session")

    from engine.utils.pseudonyms import generate_pseudonym

    for user in User.objects.all():
        if not Player.objects.filter(user=user).exists():
            identifier = user.username
            pseudonym = generate_pseudonym(
                identifier,
                is_guest=False
            )
            Player.objects.create(
                user=user,
                domain_identifier=identifier,
                pseudonym=pseudonym,
                is_guest=False
            )

    guest_sessions = Session.objects.filter(user__isnull=True)

    for session in guest_sessions:
        guest_identifier = session.guest_username

        if guest_identifier and not Player.objects.filter(domain_identifier=guest_identifier).exists():

            pseudonym = generate_pseudonym(
                guest_identifier,
                is_guest=True
            )
            Player.objects.create(
                user=None,
                domain_identifier=guest_identifier,
                pseudonym=pseudonym,
                is_guest=True
            )

def reverse_players_population(apps, schema_editor):
    Player = apps.get_model("engine", "Player")
    Player.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_identifier", models.CharField(max_length=64, unique=True)),
                ("pseudonym", models.CharField(max_length=64, unique=True)),
                ("is_guest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="engine.player",
            ),
        ),
        migrations.CreateModel(
            name="PlayerSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_skill_level", models.PositiveIntegerField(default=1)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="engine.player",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.DeleteModel(
            name="UserSkillProfile",
        ),
        migrations.RunPython(populate_pseudonyms, reverse_code=reverse_players_population),
    ]
