# Generated by Django 6.0.7 on 2026-07-19 02:21

from django.db import migrations

def link_sessions_to_players(apps, schema_editor):
    Session = apps.get_model("engine", "Session")
    Player = apps.get_model("engine", "Player")

    auth_sessions = Session.objects.filter(user__isnull=False)
    for session in auth_sessions:
        player = Player.objects.filter(user=session.user).first()
        if player:
            session.player = player
            session.save(update_fields=["player"])

    guest_sessions = Session.objects.filter(user__isnull=True)
    for session in guest_sessions:
        player = Player.objects.filter(domain_identifier=session.guest_username, is_guest=True).first()
        if player:
            session.player = player
            session.save(update_fields=["player"])

def unlink_sessions_from_players(apps, schema_editor):
    Session = apps.get_model("engine", "Session")
    Session.objects.all().update(player=None)


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_player_session_player_playerskillprofile_and_more"),
    ]

    operations = [
        migrations.RunPython(link_sessions_to_players, reverse_code=unlink_sessions_from_players),
    ]
