# Generated by Django 6.0.7 on 2026-07-19 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_alter_session_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="player",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="engine.player",
            ),
        ),
    ]
