# Generated by Django 6.0.7 on 2026-07-19 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_alter_session_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerskillprofile",
            old_name="user_skill_level",
            new_name="player_skill_level",
        ),
        migrations.AlterUniqueTogether(
            name="playerskillprofile",
            unique_together={("player", "skill")},
        ),
        migrations.RenameField(
            model_name="session",
            old_name="user_skill_level",
            new_name="player_skill_level",
        ),
        migrations.AlterField(
            model_name="playerskillprofile",
            name="player",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="engine.player",
            ),
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="user_response",
            field=models.CharField(
                help_text="Player's submitted response.", max_length=255
            ),
        ),
        migrations.RemoveField(
            model_name="playerskillprofile",
            name="user",
        ),
    ]
