# Generated by Django 6.0.7 on 2026-07-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "engine",
            "0007_rename_user_skill_level_playerskillprofile_player_skill_level_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="promptresponse",
            old_name="user_response",
            new_name="player_response",
        ),
    ]
