# Generated by Django 6.0.7 on 2026-07-19 03:39

from django.db import migrations

def port_guest_usernames_to_players(apps, schema_editor):
    Session = apps.get_model("engine", "Session")
    Player = apps.get_model("engine", "Player")

    guest_sessions = Session.objects.filter(player__isnull=True)

    for session in guest_sessions:
        guest_identifier = getattr(session, "guest_username", None)

        if not guest_identifier:
            guest_identifier = str(session.end_time)

        if guest_identifier:
            player, created = Player.objects.get_or_create(
                domain_identifier=guest_identifier,
                is_guest=True,
                defaults={
                    "player": None,
                    "pseudonym": guest_identifier[:50]
                }
            )

            session.player = player
            session.save(update_fields=["player"])

def reverse_guest_port(apps, schema_editor):
    Session = apps.get_model("engine", "Session")
    Session.objects.all().update(player=None)

class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0008_rename_user_response_promptresponse_player_response"),
    ]

    operations = [
        migrations.RunPython(port_guest_usernames_to_players, reverse_code=reverse_guest_port)
    ]
