# Generated by Django 6.0.7 on 2026-07-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_migrate_guest_usernames_to_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="guest_username",
        ),
        migrations.AlterField(
            model_name="session",
            name="player_skill_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Player's skill level at the time of the session.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="engine.skilllevel",
            ),
        ),
    ]
