# Generated by Django 6.0.7 on 2026-07-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0010_remove_session_guest_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="correct_response_array",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="correct_response_number",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="correct_response_string",
        ),
    ]
