# Generated by Django 6.0.7 on 2026-07-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0011_remove_prompt_correct_response_array_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptresponse",
            name="interaction_config",
        ),
    ]
