# Generated by Django 6.0.7 on 2026-07-22 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models

def gen_unique_uuids(apps, schema_editor):
    Player = apps.get_model("engine", "Player")
    for row in Player.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0012_remove_promptresponse_interaction_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="domain_identifier",
        ),
        migrations.RemoveField(
            model_name="player",
            name="id",
        ),
        migrations.AddField(
            model_name="player",
            name="uuid",
            field=models.UUIDField(
                null=True, blank=True,
            ),
        ),
        migrations.RunPython(gen_unique_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="player",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="pseudonym",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="playerskillprofile",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_profiles",
                to="engine.player",
            ),
        ),
        migrations.AlterField(
            model_name="playerskillprofile",
            name="player_skill_level",
            field=models.PositiveIntegerField(),
        ),
    ]
